name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --extra dev
    
    - name: Lint with flake8
      run: |
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Type check with mypy
      run: |
        uv run mypy . --ignore-missing-imports

  demo-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync
    
    - name: Test CLI commands
      run: |
        uv run rllib-trading-arena --help
        uv run rllib-trading-arena train --help
        uv run rllib-trading-arena evaluate --help
        uv run rllib-trading-arena demo --help
    
    - name: Test training command
      run: |
        timeout 300 uv run rllib-trading-arena train --iterations 10
      timeout-minutes: 5
    
    - name: Test demo command
      run: |
        timeout 300 uv run rllib-trading-arena demo --iterations 5
      timeout-minutes: 5
    
    - name: Test evaluation (requires trained model)
      run: |
        # Use the model from training step above
        timeout 120 uv run rllib-trading-arena evaluate --episodes 2
      timeout-minutes: 3
    
    - name: Test dashboard CLI
      run: |
        uv run trading-dashboard --help
        # Test dashboard startup (kill after 10 seconds)
        timeout 10 uv run trading-dashboard --port 8502 || true
      timeout-minutes: 1

